cache:
  paths:
    - public

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build:
  stage: build
  image: 
    name: reg.411lab.xyz/docker/klakegg/hugo:debian
    entrypoint: [""]
  script:
    - hugo --minify

deploy:
  stage: deploy
  needs: [build]
  image:
    name: reg.411lab.xyz/docker/library/node:16
  script:
    - npm install -g wrangler
    - wrangler --version
    - wrangler pages publish public --project-name=blog --branch=main
