default:
  tags: 
    - docker

cache:
  paths:
    - public

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build:
  stage: build
  image: 
    name: klakegg/hugo:debian
    entrypoint: [""]
  script:
    - hugo --minify

deploy:
  stage: deploy
  needs: [build]
  image:
    name: node:16
  script:
    - npm install -g wrangler
    - wrangler --version
    - echo $TEST
    - wrangler pages publish public --project-name=blog --branch=main
